import type { AdminOverview } from "./admin-overview.ts";
import type { KillSwitchState } from "./kill-switch.ts";
import type { OperatingNorthSnapshot } from "./operating-north.ts";

export type AdminPanelWorkflowStepId =
  | "workflow"
  | "overview"
  | "openclaw"
  | "clusters"
  | "fleet"
  | "audit"
  | "learning"
  | "reports"
  | "safety";

export type AdminPanelStepStatus = "ready" | "needs_review" | "blocked";

export interface AdminPanelWorkflowStep {
  id: AdminPanelWorkflowStepId;
  order: number;
  navLabel: string;
  title: string;
  operatorQuestion: string;
  purpose: string;
  dataSources: string[];
  evidenceToShow: string[];
  status: AdminPanelStepStatus;
  statusReason: string;
  nextStepId?: AdminPanelWorkflowStepId;
}

export interface AdminPanelWorkflow {
  generatedAt: string;
  phase: "5.4C-admin-panel-workflow";
  mode: "read_only";
  title: "Ruta operativa del panel Delivrix";
  summary: string;
  readBoundary: {
    allowedMethods: ["GET"];
    blockedMethods: ["POST", "PUT", "PATCH", "DELETE"];
    allowedEndpoints: string[];
  };
  steps: AdminPanelWorkflowStep[];
}

export interface AdminPanelWorkflowInput {
  overview: AdminOverview;
  operatingNorth: OperatingNorthSnapshot;
  killSwitch: KillSwitchState;
  now?: Date;
}

const allowedEndpoints = [
  "/health",
  "/v1/admin/overview",
  "/v1/admin/clusters",
  "/v1/admin/workflow",
  "/v1/openclaw/learning-plan",
  "/v1/operating-north",
  "/v1/kill-switch"
];

export function buildAdminPanelWorkflow(input: AdminPanelWorkflowInput): AdminPanelWorkflow {
  const steps: AdminPanelWorkflowStep[] = [
    {
      id: "workflow",
      order: 1,
      navLabel: "Ruta",
      title: "Ruta operativa",
      operatorQuestion: "Que debe revisar primero el operador?",
      purpose: "Ordenar la lectura del sistema antes de entrar a detalles.",
      dataSources: ["/v1/admin/workflow"],
      evidenceToShow: [
        "secuencia de revision",
        "frontera GET-only",
        "estado de cada seccion"
      ],
      status: "ready",
      statusReason: "Workflow contract is generated by backend.",
      nextStepId: "overview"
    },
    {
      id: "overview",
      order: 2,
      navLabel: "Overview",
      title: "Overview operativo",
      operatorQuestion: "El sistema esta saludable o requiere atencion?",
      purpose: "Mostrar estado global, alertas y resumen operacional.",
      dataSources: ["/health", "/v1/admin/overview"],
      evidenceToShow: [
        "estado general",
        "alertas",
        "jobs",
        "sender nodes",
        "resultados simulados"
      ],
      status: overviewStatus(input.overview),
      statusReason: `Admin overview state is ${input.overview.state}.`,
      nextStepId: "openclaw"
    },
    {
      id: "openclaw",
      order: 3,
      navLabel: "OpenClaw",
      title: "OpenClaw y gates",
      operatorQuestion: "Que puede observar o proponer OpenClaw sin ejecutar acciones reales?",
      purpose: "Exponer capacidades, bloqueos y gates del operador inteligente.",
      dataSources: ["/health", "/v1/operating-north"],
      evidenceToShow: [
        "fase actual",
        "acciones permitidas",
        "acciones bloqueadas",
        "gates"
      ],
      status: input.operatingNorth.liveInfrastructureWritesEnabled ? "blocked" : "ready",
      statusReason: input.operatingNorth.liveInfrastructureWritesEnabled
        ? "Live infrastructure writes are enabled and violate MVP visual boundary."
        : "Live infrastructure writes remain blocked.",
      nextStepId: "clusters"
    },
    {
      id: "clusters",
      order: 4,
      navLabel: "Clusters",
      title: "Clusters y VPS",
      operatorQuestion: "Que clusters/VPS debe administrar OpenClaw en modo supervisado?",
      purpose: "Mostrar inventario, capacidad y frontera de administracion de infraestructura.",
      dataSources: ["/v1/admin/clusters"],
      evidenceToShow: [
        "clusters",
        "sender nodes por proveedor",
        "provisioning dry-runs",
        "acciones propuestas"
      ],
      status: input.operatingNorth.liveInfrastructureWritesEnabled ? "blocked" : fleetStatus(input.overview),
      statusReason: input.operatingNorth.liveInfrastructureWritesEnabled
        ? "Live infrastructure writes are enabled and violate MVP boundary."
        : fleetStatusReason(input.overview),
      nextStepId: "fleet"
    },
    {
      id: "fleet",
      order: 5,
      navLabel: "Sender nodes",
      title: "Sender nodes",
      operatorQuestion: "Que nodos requieren atencion antes de cualquier escalamiento?",
      purpose: "Mostrar salud, estados y recomendaciones de flota.",
      dataSources: ["/v1/admin/overview"],
      evidenceToShow: [
        "health por nodo",
        "estado actual",
        "estado recomendado",
        "metricas de reputacion"
      ],
      status: fleetStatus(input.overview),
      statusReason: fleetStatusReason(input.overview),
      nextStepId: "audit"
    },
    {
      id: "audit",
      order: 6,
      navLabel: "Auditoria",
      title: "Auditoria reciente",
      operatorQuestion: "Que evidencia explica el estado actual?",
      purpose: "Mostrar acciones recientes, actor, riesgo y target.",
      dataSources: ["/v1/admin/overview"],
      evidenceToShow: [
        "eventos recientes",
        "actor",
        "accion",
        "riesgo",
        "target"
      ],
      status: input.overview.recentAuditEvents.length > 0 ? "ready" : "needs_review",
      statusReason: input.overview.recentAuditEvents.length > 0
        ? "Recent audit evidence is available."
        : "No recent audit events are available in admin overview.",
      nextStepId: "learning"
    },
    {
      id: "learning",
      order: 7,
      navLabel: "Aprendizaje",
      title: "Aprendizaje OpenClaw",
      operatorQuestion: "Como OpenClaw aprende sin auto-entrenarse ni ejecutar acciones reales?",
      purpose: "Definir evidencia, feedback humano y evals para mejorar recomendaciones.",
      dataSources: ["/v1/openclaw/learning-plan", "/v1/admin/overview"],
      evidenceToShow: [
        "fuentes permitidas",
        "fuentes excluidas",
        "etapas",
        "gates de evaluacion"
      ],
      status: input.overview.recentAuditEvents.length > 0 ? "ready" : "needs_review",
      statusReason: input.overview.recentAuditEvents.length > 0
        ? "Audit evidence exists for supervised learning loop."
        : "OpenClaw needs curated audit evidence before learning recommendations.",
      nextStepId: "reports"
    },
    {
      id: "reports",
      order: 8,
      navLabel: "Reportes",
      title: "Reportes y evidencia MVP",
      operatorQuestion: "Que puede mostrarse sin generar nuevos efectos desde UI?",
      purpose: "Explicar que el reporte final no se genera automaticamente desde el panel.",
      dataSources: ["/v1/operating-north"],
      evidenceToShow: [
        "gates hacia produccion limitada",
        "estado not_generated_from_ui",
        "bloqueo de POST automatico"
      ],
      status: "needs_review",
      statusReason: "Final report generation is intentionally not exposed as a UI GET contract yet.",
      nextStepId: "safety"
    },
    {
      id: "safety",
      order: 9,
      navLabel: "Seguridad",
      title: "Seguridad operacional",
      operatorQuestion: "Que sigue apagado por diseno?",
      purpose: "Confirmar kill switch, no email real, no infraestructura live y no writes NFC.",
      dataSources: ["/health", "/v1/kill-switch", "/v1/operating-north"],
      evidenceToShow: [
        "kill switch",
        "email real apagado",
        "infraestructura live bloqueada",
        "NFC writes bloqueado"
      ],
      status: safetyStatus(input),
      statusReason: safetyStatusReason(input),
      nextStepId: undefined
    }
  ];

  return {
    generatedAt: (input.now ?? new Date()).toISOString(),
    phase: "5.4C-admin-panel-workflow",
    mode: "read_only",
    title: "Ruta operativa del panel Delivrix",
    summary: "El panel guia al operador desde estado general hasta gates de seguridad, sin ejecutar mutaciones desde UI.",
    readBoundary: {
      allowedMethods: ["GET"],
      blockedMethods: ["POST", "PUT", "PATCH", "DELETE"],
      allowedEndpoints
    },
    steps
  };
}

function overviewStatus(overview: AdminOverview): AdminPanelStepStatus {
  if (overview.state === "critical") {
    return "blocked";
  }

  if (overview.state === "warning") {
    return "needs_review";
  }

  return "ready";
}

function fleetStatus(overview: AdminOverview): AdminPanelStepStatus {
  if (overview.health.some((decision) => decision.severity === "critical")) {
    return "blocked";
  }

  if (overview.health.some((decision) => decision.severity === "warning")) {
    return "needs_review";
  }

  return "ready";
}

function fleetStatusReason(overview: AdminOverview): string {
  const critical = overview.health.filter((decision) => decision.severity === "critical").length;
  const warning = overview.health.filter((decision) => decision.severity === "warning").length;

  if (critical > 0) {
    return `${critical} sender node health decision(s) are critical.`;
  }

  if (warning > 0) {
    return `${warning} sender node health decision(s) require review.`;
  }

  return "Sender node health is nominal.";
}

function safetyStatus(input: AdminPanelWorkflowInput): AdminPanelStepStatus {
  if (
    input.operatingNorth.delivrixSendsRealEmail
    || input.operatingNorth.liveInfrastructureWritesEnabled
    || input.operatingNorth.nfcProductionWritesEnabled
  ) {
    return "blocked";
  }

  if (input.killSwitch.enabled) {
    return "needs_review";
  }

  return "ready";
}

function safetyStatusReason(input: AdminPanelWorkflowInput): string {
  if (input.operatingNorth.delivrixSendsRealEmail) {
    return "Real Delivrix email sending is enabled and violates MVP boundary.";
  }

  if (input.operatingNorth.liveInfrastructureWritesEnabled) {
    return "Live infrastructure writes are enabled and violate MVP boundary.";
  }

  if (input.operatingNorth.nfcProductionWritesEnabled) {
    return "NFC production writes are enabled and violate MVP boundary.";
  }

  if (input.killSwitch.enabled) {
    return "Kill switch is active; operator should review incident context.";
  }

  return "Safety boundary is intact.";
}
